ALTER TABLE products
    MODIFY COLUMN price DECIMAL(12,2),
    ADD COLUMN rating DOUBLE DEFAULT 0,
    ADD COLUMN total_ratings INT DEFAULT 0,
    ADD COLUMN created_at DATETIME NULL,
    ADD COLUMN product_name VARCHAR(255),
    ADD COLUMN quantity DOUBLE,
    ADD COLUMN crop_id BIGINT,
    ADD COLUMN category VARCHAR(255),
    ADD COLUMN description VARCHAR(255),
    ADD COLUMN unit VARCHAR(20),
    ADD COLUMN city VARCHAR(255),
    ADD COLUMN state VARCHAR(255),
    ADD COLUMN country VARCHAR(255),
    ADD COLUMN image_url VARCHAR(500),
    ADD COLUMN video_url VARCHAR(500),
    ADD COLUMN farmer_id BIGINT,
    ADD COLUMN available BOOLEAN DEFAULT TRUE,
    ADD CONSTRAINT fk_product_crop FOREIGN KEY (crop_id) REFERENCES crop(id),
    ADD CONSTRAINT fk_product_farmer FOREIGN KEY (farmer_id) REFERENCES users(id);